github_user:      sendgrid
swagger_source:   sendgrid-oai
swagger_filename: oai.json

global:
    is_proxied: True
    proxy_url:  "os.environ.get('TEST_HOST')"
    host:       "https://api.sendgrid.com/v3"
    api_key:    "os.environ.get('SENDGRID_API_KEY')"