github_user: sendgrid
swagger_source: sendgrid-swagger
swagger_filename: swagger-stoplight.json

api_keys:
  custom_init: |+
      "scopes = self.sg.client.scopes"
      "        response = scopes.get()"
      "        response_json = response.json()"
      "        self.scope = response_json['scopes']"
  data: >
      data = {"name": "Python Client APIKeys Test v4000"}
  patched_data: >
      data = {"name": "Python Client APIKeys Test v4001"}
  put_data: >
      data = {"name": "Python Client APIKeys Test v4002", "scopes": self.scope}
  id: api_key_id

