github_user:      sendgrid
swagger_source:   sendgrid-swagger
swagger_filename: swagger-stoplight.json

global:
    is_proxied: True
    proxy_url:  "https://e9sk3d3bfaikbpdq7.stoplight-proxy.io/v3"
    host:       "https://api.sendgrid.com/v3"
    api_key:    "os.environ.get('SENDGRID_API_KEY')"