github_user: sendgrid
swagger_source: sendgrid-swagger
swagger_filename: swagger-stoplight.json

global:
    is_proxied: True
    proxy_url: host="https://e9sk3d3bfaikbpdq7.stoplight-proxy.io/v3"

api_keys:
  custom_init: |+
      "scopes = self.sg.client.scopes"
      "        response = scopes.get()"
      "        response_json = response.json()"
      "        self.scope = response_json['scopes']"
  data: >
      data = {"name": "Python Client APIKeys Test v4000"}
  patched_data: >
      data = {"name": "Python Client APIKeys Test v4001"}
  put_data: >
      data = {"name": "Python Client APIKeys Test v4002", "scopes": self.scope}
  id: api_key_id
  custom_class_name: APIKeys

templates:
  custom_init: " "
  data: >
      data = {"name": "Python Client Template Endpoint Test v4000"}
  patched_data: >
      data = {"name": "Python Client Template Endpoint Test v4001"}
  id: id

scopes:
  custom_init: " "

suppression:
  custom_init: " "
  final_endpoint: bounces
  full_endpoint_path: suppression.bounces
  id: email
  init_id_value: info@elmerthomas.com

bounces:
  mocked_params: 
      delete: >
          {"mock": 204}
      delete_specific: >
          {"mock": 204}
